name: Build Tesseract
on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: true
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: docker build --build-arg TESSERACT_VERSION=4.0.0 -t scotchcurry/tesseract -f backend/app/lib/lambdas/addRecipeWorker/Dockerfile .
      - 
        name: Push image to Docker Hub
        run: docker push scotchcurry/tesseract
