name: Deploy Lambda Functions

on:
  push:
    branches:
      - main # Adjust to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 'stable'
          
      - name: Install Dependencies
        run: |
          sudo apt-get install musl-tools
          
      - name: Build Lambda Functions
        run: |
          rustup target add x86_64-unknown-linux-musl
          
          cd backend/app/lib/lambdas/addRecipe
          ./build.sh
          
          cd ../addRecipeWorker
          ./build.sh

          cd ../collectRecipe
          ./build.sh

          cd ../getRecipes
          ./build.sh

          cd ../getUserRecipes
          ./build.sh

          cd ../tesseract
          ./build.sh
          
      - name: Install AWS CDK
        run: npm install -g aws-cdk
        
      - name: Deploy CDK Stack
        run: |
          cd backend/app
          npm install
          cdk deploy --require-approval never

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NFT_STORAGE_API_KEY: ${{ secrets.NFT_STORAGE_API_KEY }}
          CLOUD_CONVERT_API_KEY: ${{ secrets.CLOUD_CONVERT_API_KEY }}
